version: "3.7"
########################################################
#                ROBO DC.PAWPAM v.1.0                  #
########################################################
services:
  phpapp:
    build: ./phpapp
    image: phpapp:1.0
    container_name: phpapp
    env_file: ./.env
    environment:
      MYSQL_HOST: db
      PAWPAM_VERSION: 1.1
      REQUIRE_COMPOSER: "false"
    networks:
      - phpappnet
    ports:
      - "80:80"
    depends_on:
      - db
      # - cache
    volumes:
      - ./phpapp/src:${APP_MAIN_DIR}
      # - ./phpapp:${APP_MAIN_DIR}
      # - ./storage:${APP_STORAGE_DIR}
      # - ./logs/general:/var/log
      # - ./logs/phpapp:${APP_MAIN_DIR}/logs
    cap_add:
      - SYS_TIME
      - SYS_NICE

  db:
    build: ./database
    image: phpappdb:1.0
    container_name: db
    networks:
      - phpappnet
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    command: --character-set-server=${DB_CHARSET} --collation-server=${DB_CHARSET}_general_ci
    restart: always

  # cache:
  #     image: redis:5-alpine
  #     container_name: cache
  #     volumes:
  #         - cachedata:/data
  #     networks:
  #         - phpappnet
  #     entrypoint: redis-server --appendonly yes
  #     restart: always
  # PhpMyAdmin container - remove in production!
  # Uncomment when needed
  # phpma:
  #   image: phpmyadmin/phpmyadmin:fpm-alpine
  #   container_name: phpma
  #   networks:
  #     - phpappnet
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PMA_HOST: db
  #   depends_on:
  #     - db

networks:
  phpappnet:

volumes:
  dbdata:
    driver: local
  phpapp:
    driver: local
  # cachedata:
  #     driver: local
